### PR TITLE
refactor: decrease cognitive complexity, divide into small functions

### PR DESCRIPTION
**Pull request by ShahriyarR**
PR to make full refactoring to make it cleaner and more understandable.
* Codebase is still typed - passed the mypy.
* No breaking changes - test suite still passes.

The refactoring strategy aimed to decrease cognitive complexity, to have single responsible smaller functions, cleaner variables, and function names, and simplified if statements, etc.

> This is the first batch, in the future, I can send a few more. I believe such activity will help you.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
cheers - can you rebase and make sure it passes the pre-commit-ci checks please?

**Comment by ShahriyarR** [comment]
Now it passes pre-commit checks but fails with half of the tests: `9 failed, 9 passed`

**Comment by MarcoGorelli** [comment]
yeah at a minimum it'll have to pass the tests first it you want it reviewed

**Comment by ShahriyarR** [comment]
@MarcoGorelli 
all tests passed locally. 
pre-commit passed.

**Comment by MarcoGorelli** [comment]
hey @ShahriyarR @gurashish1singh  - thanks for your PR / comments, but I don't really have time to review, especially if it doesn't change the functionality

in the future, I'd suggest looking out for "help wanted" or "good first issue" labels for where to start contributing

closing then, but thanks anyway

**Pull request closed without merging**
