### PR TITLE
Recurse into dirs

### PR DESCRIPTION
**Pull request by petrem**
implements #17 

Following the hint about making it similar to cython-lint, I ended up dropping my initial approach and used much of the code from there (which feels a bit awkward). I hope I matched the style well enough.

I took a few liberties though:
* Created a fixture to setup test data files. Might be a bit over-engineered.
* Updated tox environment to ubuntu 20.04. In my fork, all the 18.04 jobs kept hanging. Hope it's ok.

### CODE REVIEW

**Comment by petrem** [comment]
(noticed the pre-commit fails, and config, sorry about that, will fix tomorrow)

**Comment by petrem** [comment]
@MarcoGorelli I think this is now ready and checks should be passing.

**Comment by petrem** [comment]
Hello @MarcoGorelli . Is it lack of time to review on your part (totally fine, of course), or have I done something wrong? Please ping me if I can do something; thanks!

**Comment by MarcoGorelli** [comment]
hey sorry for the delay - looks good, thanks!

**Pull request merged**
